version: "3.9"

services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    volumes:
      - ./data:/docker-entrypoint-initdb.d

