CREATE TABLE IF NOT EXISTS todo (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(255) NOT NULL,
 create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO todo(title) VALUES("IntegrationTest1");